name: plasmabio-template-bash
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel
  - sra-tools=3.1.1
  - fastqc=0.12.1
  - multiqc=1.29
  - trim-galore=0.6.5
  - hisat2=2.2.1
  - kallisto=0.46.2
  - subread=2.0.6
  - samtools=1.18

  
  
  
